---
- hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - set_fact: php_ppa=ppa:ondrej/php5
      when: php_version == '5.5'

    - set_fact: php_ppa=ppa:ondrej/php5-5.6
      when: php_version == '5.6'

    - name: Add repository for PHP.
      apt_repository: repo="{{ php_ppa }}"
      register: php_repository

    - name: Purge repository for PHP.
      apt_repository: "repo={{ item }} state=absent"
      when: "php_ppa != item and php_repository.changed"
      with_items:
        - ppa:ondrej/php5
        - ppa:ondrej/php5-5.6

    - name: Purge php packages.
      apt: name={{ item }} state=absent
      when: php_repository.changed
      with_items:
        - php5
        - libapache2-mod-php5
        - php5-mcrypt
        - php5-cli
        - php5-common
        - php5-curl
        - php5-dev
        - php5-fpm
        - php5-gd
        - php-pear
        - php-apc
        - libpcre3-dev

    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=86400

    - name: Get software for Python-based control.
      apt: "name={{ item }} state=installed"
      with_items:
        - curl
        - wget
        - python-apt
        - python-pycurl
        - build-essential

    - name: Disable the ufw firewall (since we use a simple iptables firewall).
      service: name=ufw state=stopped

    - name: Install postfix so Drupal can send emails.
      apt: name=postfix state=installed

    - name: Update ansible roles.
      shell: >
        ansible-galaxy install --force -r /etc/ansible/staging/requirements.txt
      when: update_ansible_roles

  roles:
    - { role: geerlingguy.firewall, tags: ['firewall'] }
    - { role: geerlingguy.git, tags: ['git'] }
    - { role: geerlingguy.apache, tags: ['apache'] }
    - { role: geerlingguy.mysql, tags: ['mysql'] }
    - { role: geerlingguy.varnish, tags: ['varnish'] }
    - { role: geerlingguy.memcached, tags: ['memcached'] }
    - { role: geerlingguy.php, tags: ['php'] }
    - { role: geerlingguy.php-pecl, tags: ['php'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.php-memcached, tags: ['php'] }
    - { role: geerlingguy.php-xdebug, tags: ['php'] }
    - { role: geerlingguy.php-xhprof, tags: ['php'] }
    - { role: geerlingguy.phpmyadmin, tags: ['phpmyadmin'] }
    - { role: geerlingguy.composer, tags: ['composer'] }
    - { role: geerlingguy.drush, tags: ['drush'] }
    - { role: geerlingguy.drupal-console, tags: ['drupal-console'], when: php_version.stdout.find('5.3') != 0 }
    - { role: geerlingguy.daemonize, tags: ['mail'] }
    - { role: geerlingguy.mailhog, tags: ['mail'] }
    - { role: geerlingguy.java, tags: ['solr'] }
    - { role: geerlingguy.solr, tags: ['solr'] }

  tasks:
    - name: Disable default Apache site.
      command: a2dissite 000-default
      notify: restart webserver

    - name: Ensure networking tools are installed.
      apt: "name={{ item }} state=present"
      with_items:
        - iftop
        - traceroute
        - tcpdump

    - name: Ensure performance analysis tools are installed.
      apt: "name={{ item }} state=present"
      with_items:
        - htop
        - iotop
        - sysstat # includes netstat
        - lsof
        - strace

    - name: Ensure other helpful software is installed.
      apt: "name={{ item }} state=present"
      with_items:
        - imagemagick
        - unzip

    - name: Ensure development tools are installed.
      apt: "name={{ item }} state=present"
      with_items:
        - vim
        - emacs
